### PR TITLE
Add a Test implementation of the service

### PR DESCRIPTION
**Pull request by amir**
A filesystem backed test implementation of the service

### CODE REVIEW

**Review by barambani — DISMISSED** [review]

**Review by barambani — DISMISSED** [review]

**Review by sirocchj — DISMISSED** [review]
Just wondering if we want the stub in src/main or we want to have a testkit module and have it in src/main there.. create a test for the stub itself and place in in testkit/src/test and add testkit as a test dependency in the main module.. contrived?

**Comment by amir** [comment]
> Just wondering if we want the stub in src/main or we want to have a testkit module and have it in src/main there.. create a test for the stub itself and place in in testkit/src/test and add testkit as a test dependency in the main module.. contrived?

certainly possible, but having `Test` in main project doesn't seem out of place in zio parlance. e.g., https://github.com/zio/zio-s3/blob/master/src/main/scala/zio/s3/Test.scala in `zio-s3` which this library is heavily inspired by.

**Comment by sirocchj** [comment]
> having `Test` in main project doesn't seem out of place in zio parlance

yup... I'm aware. and never been a huge fan tbh

this is good to go as is btw, can you squash and merge it?

**Comment by amir** [comment]
> yup... I'm aware. and never been a huge fan tbh

wasn't aware of that

> this is good to go as is btw, can you squash and merge it?

let me move it into a separate testkit project

**Review by sirocchj — APPROVED** [review]

**Pull request merged**
